// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineGroceryApp.Models;

public partial class Admin
{
    public int AdminId { get; set; }

    public string AdminEmail { get; set; }

    public byte[] Password { get; set; }

    public string AdminName { get; set; }

    public string AdminPhoneno { get; set; }
}